fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    postgresql: "https://github.com/puppetlabs/puppet-postgresql.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    staging: "https://github.com/nanliu/puppet-staging.git"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    java_ks: "https://github.com/puppetlabs/puppetlabs-java_ks.git"
    zypprepo: "https://github.com/deadpoint/puppet-zypprepo.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    augeasproviders_core: "https://github.com/hercules-team/augeasproviders_core.git"
    augeasproviders_sysctl: "https://github.com/hercules-team/augeasproviders_sysctl.git"
  symlinks:
    cloudera: "#{source_dir}"
